### ISSUE TITLE
Docker build issue

### ISSUE THREAD

**Issue by 4e4ensniper** [fusion-energy/openmc_plot#65]
I am trying to use docker to run openmc_plot locally, however I get the following error when building the image.
![124](https://github.com/user-attachments/assets/c37c3518-2dc7-49dc-9fd2-3dbc72f1337b)
I am using the following version of docker
Docker version 27.2.0, build 3ab4256

**Comment by shimwell** [comment]
Looks like conda can't solve the environment 

Could perhaps try changing the version of ipenmc to 0.15.0 which is the latest version

**Comment by 4e4ensniper** [comment]
I changed 0.13.3 to 0.15.0 in Dockerfile, but it didn't solve my problem.
![2](https://github.com/user-attachments/assets/4b82cce0-964d-442f-b4d4-2299b9da7b49)

**Comment by shimwell** [comment]
That is a shame, perhaps try updating the docker image from ``` continuumio/miniconda3:4.12.0``` to the latest

**Comment by 4e4ensniper** [comment]
Thank you very much for your help! 
I have also updated the line `FROM continuumio/miniconda3:4.12.0` to `FROM continuumio/miniconda3:latest` in the Dockerfile. Everything works fine now. However, I did need to manually set the port for the container, using the command `docker run -p 8501:8501 -t openmc_plot`.
